### ISSUE TITLE
[Feature request] Make double-clicking closing brackets also select

### ISSUE THREAD

**Issue by FallDownTheSystem** [antfu/vscode-smart-clicks#1]
Right now selection only works when double-clicking the opening bracket. If possible, it would be nice if the selection also worked when using the closing brackets.

e.g.
```js
class Solution {
    solve(s0: string, s1: string) <-- selection by clicking here : boolean {
        // some code
    } <-- or here
} <-- or here
```

Just an idea 🤷‍♂️

**Comment by antfu** [comment]
It's already on my todo, but for later. If you want to play with it, you can give it a shot 😉

**Comment by antfu** [comment]
OK I am doing it now
