### ISSUE TITLE
Issues when selecting text & single clicking in a specific manner

### ISSUE THREAD

**Issue by HassanZahirnia** [antfu/vscode-smart-clicks#12]
I've noticed 2 issues when trying to select few lines of codes, the gifs are self-explanatory:

![Antfu-Smart-Click-Extension-Issues](https://user-images.githubusercontent.com/15275787/159889553-064f9d55-d53d-4781-9703-ec3fea3cb55b.gif)
![Antfu-Smart-Click-Extension-Issues-2](https://user-images.githubusercontent.com/15275787/159890636-898b2e4e-b2cb-40bf-b335-91b209f40ac6.gif)

Thanks a lot for your hard work 💜🙏

**Comment by antfu** [comment]
What's your version?

**Comment by HassanZahirnia** [comment]
Sorry forgot to mention the version. `Smart Clicks v0.0.6`

**Comment by antfu** [comment]
Upgrade to the latest and try agin.

**Comment by HassanZahirnia** [comment]
Updated to latest version, it "feels" like it happens less often, but it still happens. 
![image](https://user-images.githubusercontent.com/15275787/159893195-69c8451c-e9b4-4506-93e5-2388466aa8fc.png)
![Antfu-Smart-Click-Extension-Issues-3](https://user-images.githubusercontent.com/15275787/159893459-02409125-8f47-4de9-a13e-16ffb1fa15ea.gif)

**Comment by HassanZahirnia** [comment]
Another problem is that it feels like the detection for double click needs some improvement. I noticed when I'm quickly moving the cursor around the code using mouse's left click, the extension will trigger even though I did not indent to use it ( double clicking )
![Antfu-Smart-Click-Extension-Issues-4](https://user-images.githubusercontent.com/15275787/159895571-8ae91745-0fe5-41c1-a02a-2cca6f7a51b3.gif)

**Comment by antfu** [comment]
Should be a bit better with 0.0.11. This can't be completely prevented since there is no API for actually double clicks and we are hacking the selection changes to do the detection.

**Comment by HassanZahirnia** [comment]
Thanks for the update! I can confirm the issue with select & drag seem to be gone ✅
Although just like you said the double click detection issue still exist which is a bit annoying ＞︿＜

Either way, thanks again and have a great day!

**Comment by antfu** [comment]
You could try to decrase `smartClicks.clicksInterval`
https://github.com/antfu/vscode-smart-clicks/blob/9b42c4fa598274a267d8e96df5169d6a5d2ee163/package.json#L37-L46

**Comment by HassanZahirnia** [comment]
It's weird because I tried to increase both `clicksInterval` and `triggerDelay` and the issue still persists. I even increased either of them to an absurd value like `5000`
