### ISSUE TITLE
Does not work on php files

### ISSUE THREAD

**Issue by BernhardBaumrock** [antfu/vscode-smart-clicks#13]
Hi,
looks promising but is not usable for me as all of my html files are actually .php files and there the double clicks do nothing...

**Comment by antfu** [comment]
I don't use PHP myself so I can't really help with this. But for sure open for contributions.

**Comment by BernhardBaumrock** [comment]
There's nothing special about PHP. It's the same syntax as HTML. It's just another file ending.
