### ISSUE TITLE
从右往左选择字符串的时候，会额外选择到右边的引号

### ISSUE THREAD

**Issue by Cansiny0320** [antfu/vscode-smart-clicks#3]
![20220323194248](https://user-images.githubusercontent.com/51797219/159691779-0462d998-779c-45a2-af01-490efa648d7d.gif)

**Comment by antfu** [comment]
I can't reproduce that, probably it's made by other extensions?

**Comment by Cansiny0320** [comment]
> I can't reproduce that, probably it's made by other extensions?

I'm not sure, but after I upgraded to v0.0.5, the problem didn't reappear, maybe some commit fixed it
